apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-msql
spec:
  selector:
    matchLabels:
      app: python-msql
  template:
    metadata:
      labels:
        app: python-msql
    spec:
      serviceAccountName: mysql-sa
      initContainers:
      - image: gcr.io/cr-demo-project/python-msql-init:v1.1
        name: python-msql-init
        env:
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        - name: MYSQL_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_DATABASE_USER
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_DATABASE_PASSWORD
      containers:
      - name: python-msql
        image: gcr.io/cr-demo-project/python-msql-app:v1.1
        env:
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        - name: MYSQL_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_DATABASE_USER
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_DATABASE_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
