apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: python-msql
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: python-msql
  type: LoadBalancer
status:
  loadBalancer: {}